name: Update Coffee Stats

on:
  schedule:
    - cron: '0 8 * * *'  # Daily at 8 AM UTC (10 AM SAST)
  workflow_dispatch:     # Manual trigger

jobs:
  update-coffee-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install puppeteer

      - name: Update coffee stats
        env:
          SEATTLE_COFFEE_USERNAME: ${{ secrets.SEATTLE_COFFEE_USERNAME }}
          SEATTLE_COFFEE_PASSWORD: ${{ secrets.SEATTLE_COFFEE_PASSWORD }}
        run: node .github/scripts/coffee-scraper.js

      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/coffee-stats.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update coffee stats - $(date)"
          git push